title: jeffatoptics
description: My dailynote and repository pages
show_downloads: false
logo: https://avatars.githubusercontent.com/u/94174882
google_analytics:
theme: jekyll-theme-minimal
# theme: minima
# minima:
#   skin: dark
