title: jeffatoptics
description: My dailynote and repository pages
show_downloads: false
logo: /assets/logo.jpg
google_analytics:
#theme: jekyll-theme-minimal

remote_theme: "godalming123/minimal"
color-scheme: dark
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#color-scheme: ["dark", "light", "auto" or "auto-default-dark" auto is the default setting and changes theme based on device theme, auto-default-dark is the same except if you device does not support changing theme based on device theme it will default to dark and the others are fairly self explanetory.]